packages:
  pkg:
    - tmux
    - bashtop
    - { name: python-hcloud, status: absent}
  aur: # for arch linux, packages only found in aur
    - git-extras
    - lens-bin
  pip:
    - pexpect
    - pre-commit
    - hcloud
    - gphotos-sync
