roles:
  - name: kewlfft.aur
  - name: papanito.cloudflared
  # own roles
  - src: https://git@github.com/papanito/ansible-role-git.git
    name: papanito.git
    scm: git
    version: master
  - src: https://git@github.com/papanito/ansible-role-borg.git
    name: papanito.borg
    scm: git
    version: master
  - src: https://git@github.com/papanito/ansible-role-diskmounter.git
    name: papanito.diskmounter
    scm: git
    version: master
  - src: https://git@github.com/papanito/ansible-role-systemd_notifiers.git
    name: papanito.systemd_notifiers
    scm: git
    version: main

collections:
  # Install a collection from Ansible Galaxy.
  - name: hetzner.hcloud
  - name: geerlingguy.php_roles
    source: https://galaxy.ansible.com
