- name: kewlfft.aur
- name: papanito.cloudflared
# own roles
- src: https://git@github.com/papanito/ansible-role-borg.git
  name: papanito.borg
  scm: git
  version: master
- src: https://git@github.com/papanito/ansible-role-diskmounter.git
  name: papanito.diskmounter
  scm: git
  version: master
