---
- hosts: all
  vars:
    remote_user: "{{ localuser }}"
    user: "{{ localuser }}"
    dotfiles_src: dot-files
    dotfiles_profile: personal
  roles:
    - { role: resources, stow_version: 2.2.2-5 }
