- include_tasks: packages.yml
  ignore_errors: yes
  loop: "{{ packages }}"
  loop_control:
    loop_var: package

- include_tasks: packages_aur.yml
  when: ansible_facts['os_family'] == "Archlinux"
  ignore_errors: yes
  loop: "{{ aur_packages }}"
  loop_control:
    loop_var: aur_package

# cd Photos
# pipenv install gphotos-sync
# pipenv run gphotos-sync ~/Pictures/Photos