
- name: Get source folder for private config files
  set_fact:
    source_location: "{{ lookup('env', 'PWD') }}/resources/config-files/{{ dotfiles_profile }}"

- name: Get all stow packages for profile '{{ dotfiles_profile }}'
  find:
    paths: "{{ source_location }}"
    file_type: directory
  register: packages

- name: Symlink private config files
  shell: stow -d "{{ source_location }}" -t ~/ {{ item.path | basename }} -R # noqa 305 301
  loop: "{{ packages.files }}"