

- name: Set resource_folder
  set_fact:
    resource_folder: "{{ item.key }}"

- name: Get source folder for {{ resource_folder }} and profile {{ dotfiles_profile }}
  set_fact:
    source_location: "{{ lookup('env', 'PWD') }}/resources/{{ resource_folder }}/{{ dotfiles_profile }}"

- name: Get source folder for {{ resource_folder }}
  set_fact:
    source_location: "{{ lookup('env', 'PWD') }}/resources/{{ resource_folder }}"
  when: item.value.no_profile is defined and item.value.no_profile | bool

- name: Get all stow packages'
  find:
    paths: "{{ source_location }}"
    file_type: directory
  register: packages

- name: Symlink files and folders for {{ resource_folder }}
  include_tasks: stow.yml
  loop: "{{ packages.files }}"
