- name: Install packages
  become: true
  ansible.builtin.package:
    name: "{{ item }}"
    state: latest # noqa 403
  with_items:
    - stow
    - chezmoi
  tags:
    - dotfiles

- name: Initialize chezmoi
  ansible.builtin.import_tasks:
    file: chezmoi.yml
  tags:
    - chezmoi
    - dotfiles