- name: Install stow
  become: true
  package: name={{ item }} state=latest # noqa 403
  with_items:
    - stow

- name: Install resource folder
  include_tasks: install_resources.yml
  loop: "{{ resource_folders | dict2items }}"
