- name: Set stow package name
  set_fact:
    package_name: "{{ item.path | basename }}"

- name: Set stow target dir
  set_fact:
    stow_target_default: "{{ resource_folders[resource_folder][package_name] }}"
  when: resource_folders[resource_folder][package_name] is defined

- name: Symlink {{ package_name }} to {{ stow_target_default }} from {{ source_location }} # noqa 301 305
  shell: stow -d "{{ source_location }}" -t {{ stow_target_default }} {{ package_name }} -R
