hostname: proxmox
iface: 
  name: eno1 
ipv4:
  address: 144.76.74.177
  netmask: 255.255.255.224
  netmask_int: 27
  gateway: 144.76.74.161
  network: 144.76.69
ipv6:
  address: 2a01:4f8:191:92b0::2
  netmask: 64
  gateway: fe80::1
vlan:
  id: 4000
  address: 192.168.100.4
  netmask: 255.255.255.0
gluster:
  bricks:
    brick:
      disk: /dev/md3
      path: /data/gluster/brick1
      vgname: "vg_md3"
      thinpoolsize: '1.65T'