- hosts: all
  vars:
  - backup_name: clawfinger
  - backup_engine: restic
  - backup_target_dir: ""

  tasks:
  - name: Set `target_location`
    set_fact:
      target_location: "{{ backup_restic_repo }}:{{ backup_target_dir }}"
  - name: Show backups
    expect:
      command: restic -r {{ target_location }}/{{ backup_name }} list snapshots
      responses:
        passphrase: "{{ backup_encryption_key }}"
    register: backups

  - name: Print backup status
    debug:
      var: backups.stdout_lines