- hosts: all
  vars:
  - backup_name: clawfinger
  - backup_engine: restic
  - backup_target_dir: ""
  - backup_schedule: "*-*-* 06:20:00"
  - backup_systemd_on_failure: systemd-desktop-notifier@%N.service,systemd-googlechat-notifier@%N.service
  - backup_script_user: root
  - backup_script_group: wheel
  - backup_systemd_user: root
  - backup_systemd_group: wheel

  roles:
  - role: papanito.backup
