- hosts: localhost
  name: Setup zerotier network on hosts
  vars:
    zerotier_network_id: "{{ zerotier_networkid }}"
    zerotier_api_accesstoken: "{{ zerotier_accesstoken }}"
    hostname: clawfinger
    zerotier_member_ip_assignments: ["172.22.100.55"]
    resources_path: "{{playbook_dir}}/../resources"
    hosts_file: /etc/hosts
    domain_intra: intra

  roles:
    - { role: m4rcu5nl.zerotier-one, become: true }

  # https://linuxhint.com/list_installed_packages_pacman_arch_linux/
  # pacman -Qe | awk '{print $1}'s
  pre_tasks:
    - name: add external ip to hosts file
      lineinfile:
        path: "{{ hosts_file }}"
        regexp: "{{ hostvars[item]['ipv4']['address'] }}"
        line: "{{ hostvars[item]['ipv4']['address'] }}    {{ hostvars[item]['hostname'] }}"
        create: yes
      with_items: "{{ groups['servers'] }}"
      delegate_to: localhost
    - name: add zerotier ip to hosts file
      lineinfile:
        path: "{{ hosts_file }}"
        regexp: "{{ hostvars[item]['zerotier_member_ip_assignments'][0] }}"
        line: "{{ hostvars[item]['zerotier_member_ip_assignments'][0] }}   {{ hostvars[item]['hostname'] }}.{{domain_intra}}"
        create: yes
      with_items: "{{ groups['servers'] }}"
      delegate_to: localhost
    - name: install packages
      action: >
        {{ ansible_pkg_mgr }} name={{ query('lines', 'cat {{ resources_path }}/clients/{{ hostname }}_pkgs.txt') }} state=present update_cache=yes